name = "palimpsest"
product-name = "Palimpsest"
identifier = "io.github.parazeeknova.palimpsest"
category = "DeveloperTool"
version = "0.0.1"
authors = ["parazeeknova"]
license-file = "LICENSE"
out-dir = "dist"
formats = ["app", "dmg", "appimage", "deb", "rpm", "pacman", "nsis", "wix"]

[[binaries]]
path = "target/release/palimpsest"
main = true

[linux]
depends = ["libgtk-3-0", "libxcb-render0", "libxcb-shape0", "libxcb-xfixes0", "libxkbcommon-x11-0"]

[deb]
depends = ["libgtk-3-0", "libxcb-render0", "libxcb-shape0", "libxcb-xfixes0", "libxkbcommon-x11-0"]

[appimage]
bundle-media-framework = false

[windows]
digest-algorithm = "sha256"

[nsis]
display-language-selector = true
